# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-AuthLDAPBind
version:      0.02
version_from: lib/Apache/AuthLDAPBind.pm
installdirs:  site
requires:
    Apache::Constants:             0
    Net::LDAP:                     0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
